routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'UsersController@index');

//ユーザー登録
Route::get('signup','Auth\RegisterController@showRegistrationForm')->name('signup');
Route::post('signup','Auth\RegisterController@register')->name('signup.post');
Route::get('login','Auth\LoginController@showLoginForm')->name('login');
Route::post('login','Auth\LoginController@login')->name('login.post');
Route::get('logout','Auth\LoginController@logout')->name('logout');

Route::resource('users','UsersController',['only'=>['show']]);

Route::group(['prefix'=>'users/{id}'], function() {
    Route::get('followings', 'UsersController@followings')->name('followings');
    Route::get('followers','UsersController@followers')->name('followers');
});

Route::group(['middleware' => 'auth'], function() {
    Route::put('users','UsersController@rename')->name('rename');
    
    Route::group(['prefix'=>'users/{id}'], function() {
        Route::post('follow', 'UserFollowController@store')->name('follow');
        Route::delete('unfollow','UserFollowController@destroy')->name('unfollow');
});

    Route::resource('rest','RestappController', ['only' => ['index', 'show', 'create', 'store', 'destroy']]);

    Route::resource('movies', 'MoviesController',['only'=>['create','store','destroy']]);
    
    
});

resources/views/commons/error_messages.blade.php
@if (count($errors) > 0)
    <ul class="alert alert-danger">
        @foreach ($errors->all() as $error)
            <li class="ml-4">{{ $error }}</li>
        @endforeach
    </ul>
@endif

resources/views/commons/footer.blade.php
<footer class="mt-5">
        <nav class="navbar navbar-light bg-light justify-content-center">
            <div class="navbar-brand m-0">© QuestAcademia, All rights reserved.</div>
        </nav>
</footer>

resources/views/commons/header.blade.php
<header class="mb-5">

    <nav class="navbar navbar-expand-lg navbar-light bg-light">

        <a class="navbar-brand" href="/">YouTube-Curation</a>

        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#nav-bar">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="nav-bar">
            <ul class="navbar-nav mr-auto"></ul>
            <ul class="navbar-nav">
                
                @if (Auth::check())
                
                    <li class="nav-item">{!! link_to_route('logout', 'ログアウト', [], ['class' => 'nav-link']) !!}</li>
                    <li class="nav-item"><a href="" class="nav-link">マイページ</a></li>
                    <li class="nav-item">{!! link_to_route('movies.create','動画登録する',['id'=>Auth::id()],['class'=>'nav-link']) !!}</li>
                    
                @else
                
                    <li class="nav-item">{!! link_to_route('signup', '新規ユーザ登録', [], ['class' => 'nav-link']) !!}</li>
                    <li class="nav-item">{!! link_to_route('login', 'ログイン', [], ['class' => 'nav-link']) !!}</li>
                    <li class="nav-item">{!! link_to_route('movies.create','動画を登録する',['id'=>Auth::id()],['class'=>'nav-link']) !!}</li>
                @endif
                
            </ul>
        </div>

    </nav>

</header>